<?xml version="1.0"?>


<robot name="mmuav" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="body_mesh_file" value="3DR_ArducopterArms.dae" />
  <xacro:property name="mass" value="2.5" />  <!-- [kg] -->

  <xacro:property name="body_width" value="0.471" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.3158" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.01" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.314" /> <!-- [m] -->
  
  <xacro:property name="rotor_offset_top" value="0.04579" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1524" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg*m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant" value="0.0125" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1475" /> <!-- [rad/s] -->

  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <xacro:property name="imu_mass" value="0.02"/>
  <xacro:property name="imu_size" value="0.01"/>

  <xacro:property name="sin45" value="0.7071" />
  <xacro:property name="cos45" value="0.7071" />
  <xacro:property name="PI" value="3.14" />

    <!-- Manipulator properties-->
  <xacro:property name="link_length" value="0.5" />
  <xacro:property name="link_mass" value="0.1"/>
  <xacro:property name="link_width" value="0.05" />
  <xacro:property name="link_mesh_file" value="AX12.dae" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia 
      ixx="0.05197456" ixy="-0.00278118" ixz="-0.00000212" 
      iyx="-0.00278118" iyy="0.05197467" iyz="-0.00000110"
      izx="-0.00000212" izy="-0.00000110" izz="0.09682843" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=5mm, width=31mm -->
  <xacro:property name="rotor_inertia">
    <inertia 
    ixx="${1/12 * mass_rotor * (0.031 * 0.031 + 0.005 * 0.005) * rotor_velocity_slowdown_sim}" 
    iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.005 * 0.005) * rotor_velocity_slowdown_sim}" 
    izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.031 * 0.031) * rotor_velocity_slowdown_sim}" 
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <xacro:property name="imu_inertia">
    <inertia 
    ixx="${(imu_mass * imu_size * imu_size)/6}" 
    iyy="${(imu_mass * imu_size * imu_size)/6}" 
    izz="${(imu_mass * imu_size * imu_size)/6}" 
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find mmuav_description)/urdf/multirotor_base.urdf.xacro" />
  
  <!-- Instantiate multirotor_base_macro once-->
  <xacro:multirotor_base_macro
    robot_namespace="$(arg name)"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    mesh_file="${body_mesh_file}">
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <origin xyz="${cos45*arm_length} ${sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <origin xyz="${cos45*arm_length} ${-sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <origin xyz="${-cos45*arm_length} ${sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <origin xyz="${-cos45*arm_length} ${-sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

   <!-- Adding left manipulator -->
  <xacro:manipulator
    link_length="${link_length}"
    link_width="${link_width}"
    link_mass="${link_mass}"
    link_mesh_file="${link_mesh_file}"
    parent="base_link"
    suffix="left">
    <axis xyz="0 1 0" />
    <origin xyz="-0.11188 0.11206 -0.07349" rpy="-1.57079632679 0 0"/>  
  </xacro:manipulator>

     <!-- Adding right manipulator -->
  <xacro:manipulator
    link_length="${link_length}"
    link_width="${link_width}"
    link_mass="${link_mass}"
    link_mesh_file="${link_mesh_file}"
    parent="base_link"
    suffix="right">
    <axis xyz="0 1 0" />
    <origin xyz="0.11205 -0.11188 -0.07349" rpy="-1.57079632679 0 0"/>
  </xacro:manipulator>

  <!-- Add transmission for joints--> 
  <xacro:transmisija 
    trans_number="0" 
    joint_name="joint_q1_left">
  </xacro:transmisija>    

  <xacro:transmisija 
    trans_number="1"
    joint_name="joint_q2_left">
  </xacro:transmisija>

  <xacro:transmisija 
    trans_number="2" 
    joint_name="joint_q3_passive_left">
  </xacro:transmisija>

  <xacro:transmisija 
    trans_number="3"
    joint_name="joint_q1_right">
  </xacro:transmisija>

  <xacro:transmisija 
    trans_number="4"
    joint_name="joint_q2_right">
  </xacro:transmisija>

    <xacro:transmisija 
    trans_number="5"
    joint_name="joint_q3_passive_right">
  </xacro:transmisija>

</robot>