<?xml version="1.0"?>


<robot name="mmuav" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="body_mesh_file" value="3DR_ArducopterExtendedLegs.dae" />
  <xacro:property name="mass" value="2.5" />  <!-- [kg] -->

  <xacro:property name="body_width" value="0.471" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.3158" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.01" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.314" /> <!-- [m] -->
  
  <xacro:property name="rotor_offset_top" value="0.04579" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1524" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg*m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1475" /> <!-- [rad/s] -->

  <!--xacro:property name="rotor_drag_coefficient" value="8.06428e-05" /-->
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <xacro:property name="imu_mass" value="0.02"/>
  <xacro:property name="imu_size" value="0.01"/>

  <xacro:property name="sin45" value="0.7071" />
  <xacro:property name="cos45" value="0.7071" />
  <xacro:property name="PI" value="3.14" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia 
      ixx="0.05197456" ixy="-0.00278118" ixz="-0.00000212" 
      iyx="-0.00278118" iyy="0.05197467" iyz="-0.00000110"
      izx="-0.00000212" izy="-0.00000110" izz="0.09682843" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=5mm, width=31mm -->
  <xacro:property name="rotor_inertia">
    <inertia 
    ixx="${1/12 * mass_rotor * (0.031 * 0.031 + 0.005 * 0.005) * rotor_velocity_slowdown_sim}" 
    iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.005 * 0.005) * rotor_velocity_slowdown_sim}" 
    izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.031 * 0.031) * rotor_velocity_slowdown_sim}" 
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <xacro:property name="imu_inertia">
    <inertia 
    ixx="${(imu_mass * imu_size * imu_size)/6}" 
    iyy="${(imu_mass * imu_size * imu_size)/6}" 
    izz="${(imu_mass * imu_size * imu_size)/6}" 
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find mmuav_description)/urdf/multirotor_base.urdf.xacro" />
  
  <!-- Instantiate multirotor_base_macro once-->
  <xacro:multirotor_base_macro
    robot_namespace="$(arg name)"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    mesh_file="${body_mesh_file}">
    <origin xyz="0 0 0" rpy="0 0 ${-PI/4}"/>
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <xacro:property name="land_gear_inertia">
    <inertia
    ixx="1e-6"
    iyy="1e-6"
    izz="1e-6"
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <xacro:landing_gear
      parent="base_link"
      gear_num = "1"
      mass = "1e-6"
      dim_x = "0.8"
      dim_y = "0.1"
      dim_z = "0.05">
      <origin xyz="0 -0.325 -0.075" rpy="0 0 0" />
      <xacro:insert_block name="land_gear_inertia"/>
  </xacro:landing_gear>

  <xacro:landing_gear
      parent="base_link"
      gear_num = "2"
      mass = "1e-6"
      dim_x = "0.8"
      dim_y = "0.1"
      dim_z = "0.05">
      <origin xyz="0 0.325 -0.075" rpy="0 0 0" />
      <xacro:insert_block name="land_gear_inertia"/>
  </xacro:landing_gear>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <origin xyz="${1*arm_length} ${0*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <origin xyz="${0*arm_length} ${1*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <origin xyz="${-1*arm_length} ${0*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <origin xyz="${0*arm_length} ${-1*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

   <!-- Adding left manipulator -->
  <xacro:manipulator
    parent="base_link"
    suffix="left">
    <axis xyz="0 1 0" />
    <origin xyz="0 -0.1583424671 -0.07349" rpy="0 ${PI} 0"/>
  </xacro:manipulator>

     <!-- Adding right manipulator -->
  <xacro:manipulator
    parent="base_link"
    suffix="right">
    <axis xyz="0 1 0" />
    <origin xyz="0 0.1583424671 -0.07349" rpy="0 ${PI} ${PI}"/>
  </xacro:manipulator>

  <!-- Add transmission for joints-->     
  <xacro:transmisija 
    trans_number="0" 
    joint_name="joint_dynamixel1_left">
  </xacro:transmisija>    

  <xacro:transmisija 
    trans_number="1"
    joint_name="joint_dynamixel2_left">
  </xacro:transmisija>

  <xacro:transmisija 
    trans_number="2"
    joint_name="joint_dynamixel1_right">
  </xacro:transmisija>

  <xacro:transmisija 
    trans_number="3"
    joint_name="joint_dynamixel2_right">
  </xacro:transmisija>

  <xacro:transmisija 
    trans_number="4"
    joint_name="joint_gripper2_right">
  </xacro:transmisija>

  <xacro:transmisija 
    trans_number="5"
    joint_name="joint_gripper2_left">
  </xacro:transmisija>

            <!-- delete afteR-->
    <link name='link_screw'>
      
      <inertial>
        <mass value="0.5" />
        <origin rpy="0 0 0" xyz="0.02100388 0.01819119 0.05027511"/>
        <inertia
          ixx="0.00020051" ixy="0" ixz="-0.00000019"
          iyx="0" iyy="0.00020054" iyz="0.00000001"
          izx="-0.00000019" izy="0.00000001" izz="0.00006377"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/screw.dae"
            scale="1 1 1" />
        </geometry>
      </visual>

      <collision name='collision'>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mmuav_description/meshes/screw.dae"
            scale="1 1 1" />
        </geometry>
      </collision>
    </link>


    <joint name="joint_screw" type="fixed">
        <origin xyz="0.023 0.006 0.0385" rpy="${PI} 0 ${PI/6}" />
        <parent link="link_gripper2_left"/>
        <child link="link_screw"/>
    </joint>

  <!-- Camera properties -->
  <!--xacro:property name="camera_link" value="0.05" />
  <xacro:property name="camera_inertia">
    <inertia
    ixx="1e-8"
    iyy="1e-8"
    izz="1e-8"
    ixy="0.0" ixz="0.0" iyz="0.0" />
  </xacro:property>
  <xacro:property name="camera_mass" value="1e-5"/>

  <xacro:cam
    camera_link="${camera_link}"
    camera_mass="${camera_mass}"
    parent="base_link">
    <origin xyz="0 0 -0.5" rpy="0 ${-PI/2} 0"/>
    <xacro:insert_block name="camera_inertia"/>
  </xacro:cam-->

</robot>